services:
  - type: web
    name: mandi-management-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mandi-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://mandi-management-system.onrender.com

databases:
  - name: mandi-db
    plan: free
    databaseName: mandi_management
    user: mandi_user